from snn.network import Network

class Pattern_Matcher(Network):
    def __init__(self, pattern):
        super().__init__(3, 1)
        self.add_neuron(("Clock 0", 1, 0))
        self.add_neuron(("Clock 1", 1, 0))
        self.add_neuron(("Clock 2", 1, 0))
        self.add_synapse(("Input 2", "Clock 0", 1))
        l = 4 + sum([(1 + int(pattern[len(pattern) - 1 - i])) / (3 ** i) for i in range(len(pattern))])
        u = l + 1 / (3 ** (len(pattern) - 1))
        d = 1/3
        self.add_neuron(("Upper 0", u, d))
        self.add_neuron(("Lower 0", l, d))
        self.add_neuron(("Upper 1", u, d))
        self.add_neuron(("Lower 1", l, d))
        self.add_neuron(("Upper 2", u, d))
        self.add_neuron(("Lower 2", l, d))
        self.add_synapse(("Clock 0", "Upper 0", 4))
        self.add_synapse(("Clock 0", "Lower 0", 4))
        self.add_synapse(("Clock 1", "Upper 1", 4))
        self.add_synapse(("Clock 1", "Lower 1", 4))
        self.add_synapse(("Clock 2", "Upper 2", 4))
        self.add_synapse(("Clock 2", "Lower 2", 4))
        self.add_synapse(("Input 0", "Upper 0", 1))
        self.add_synapse(("Input 1", "Upper 0", 1))
        self.add_synapse(("Input 0", "Lower 0", 1))
        self.add_synapse(("Input 1", "Lower 0", 1))
        self.add_synapse(("Input 0", "Upper 1", 1))
        self.add_synapse(("Input 1", "Upper 1", 1))
        self.add_synapse(("Input 0", "Lower 1", 1))
        self.add_synapse(("Input 1", "Lower 1", 1))
        self.add_synapse(("Input 0", "Upper 2", 1))
        self.add_synapse(("Input 1", "Upper 2", 1))
        self.add_synapse(("Input 0", "Lower 2", 1))
        self.add_synapse(("Input 1", "Lower 2", 1))
        self.add_neuron(("AND", 1, 0))
        self.add_synapse(("Upper 0", "AND", -1))
        self.add_synapse(("Upper 0", "AND", -1))
        self.add_synapse(("Lower 0", "AND", 1))
        self.add_synapse(("Lower 0", "AND", 1))
        self.add_synapse(("Upper 1", "AND", -1))
        self.add_synapse(("Upper 1", "AND", -1))
        self.add_synapse(("Lower 1", "AND", 1))
        self.add_synapse(("Lower 1", "AND", 1))
        self.add_synapse(("Upper 2", "AND", -1))
        self.add_synapse(("Upper 2", "AND", -1))
        self.add_synapse(("Lower 2", "AND", 1))
        self.add_synapse(("Lower 2", "AND", 1))
        self.add_synapse(("AND", "Output 0", 1))
        self.setup_network()

    def __call__(self, *args, **kwargs):
        return self.step(*args, **kwargs)

matcher = Pattern_Matcher("101")
print(matcher.step([0, 0, 1]))
print(matcher.step())
